
export const Client = [
    {
        "image":"/images/Clients/client1.png",
        "url":"https://www.adnoc.ae/"
    },
    {
        "image":"/images/Clients/client7.png",
        "url":"https://www.rcuae.ae/"
    },
    {
        "image":"/images/Clients/client8.png",
        "url":"https://www.emiratesislamic.ae/eng/"
    },
    {
        "image":"/images/Clients/client6.png",
        "url":"https://www.gdrfad.gov.ae/ar/sites/default/files"
    },
    {
        "image":"/images/Clients/client9.png",
        "url":"https://www.uaeu.ac.ae/ar/"
    },
    {
        "image":"/images/Clients/client10.png",
        "url":"https://alec.ae/"
    },
    {
        "image":"/images/Clients/client11.svg",
        "url":"https://www.dubaipolice.gov.ae/wps/portal/home/home"
    },
    {
        "image":"/images/Clients/client12.svg",
        "url":"https://www.sharjahairport.ae/ar/"
    },
    {
        "image":"/images/Clients/client13.svg",
        "url":"https://www.abudhabiairport.ae/en"
    },
    {
        "image":"/images/Clients/client19.png",
        "url":"https://www.mohap.gov.ae/ar/Pages/default.aspx"
    },
    {
        "image":"/images/Clients/client16.png",
        "url":"https://dpwglobalprod.azureedge.net/"
    },
    {
        "image":"/images/Clients/client14.svg",
        "url":"https://cdn.emaar.com/"
    },
    {
        "image":"/images/Clients/partner1.png",
        "url":"http://www.ehong.ae"
    },
    {
        "image":"/images/Clients/client17.png",
        "url":"https://www.dubaicustoms.gov.ae/ar/Pages/default.aspx/"
    },
    {
        "image":"/images/Clients/client18.gif",
        "url":"https://www.emiratesnbd.com/en/"
    },
    {
        "image":"/images/Clients/client20.jfif",
        "url":"#"
    },
    
];